# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c6c9a3696b55d82dd8488e38c68e00040071d447b824c396848af8ac81fe5baa2049de05c7c09635c5ca00e3a3420f0b07415063c4a89fe7ff1eca69a3bc725

test:
  secret_key_base: 7741cc6d1b86cb2e46450c0cf7f3ca9b3741f4346098d572110a6cfda7f432ab1d71964b440d59730cabfb92519ce01c5ff93fa2fa004c9ccb7d3fc87dccb8e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
